name: Lint Commit Messages

on:
  - pull_request

jobs:
  lint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: michaelgwelch/commitlint-github-action@add-exclude-target-branch
        with:
          excludeTargetBranch: 'true'
          helpURL: https://github.com/johnsoncontrols/metasys-rest-api/#committing
